DROP TABLE IF EXISTS TB_HEROIS

CREATE TABLE TB_HEROIS(
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    NOME TEXT NOT NULL,
    PODER TEXT NOT NULL,
)


INSERT INTO TB_HEROIS (NOME, PODER)
VALUES
    ('FLASH','VELOCIDADE'),
    ('ACQUAMAN','AQUATICO'),
    ('BATMAN','DINHEIRO')
;

SELECT * FROM TB_HEROIS;
SELECT * FROM TB_HEROIS WHERE NOME ='FLASH';



UPDATE TB_HEROIS
SET NOME='SUPERMAN', PODER='FORCA'
WHERE ID = 1;


DELETE FROM TB_HEROIS WHERE ID = 3;